import { IMainNav } from '@Types/MainNav';
import { IUserMenu } from '@Types/UserMenu';

export const mainNavList: IMainNav[] = [
  {
    title: 'Акции и скидки',
    icon: 'sale.svg',
    link: 'catalog',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Акции и скидки', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Диваны и кресла',
    icon: 'divans.svg',
    link: 'ideas',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Диваны и кресла', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Шкафы',
    icon: 'wardrobe.svg',
    link: 'about',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Шкафы', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Спальня',
    icon: 'bedroom.svg',
    link: 'store',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Спальня', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Гостиная',
    link: 'living-room',
    icon: 'hallway.svg',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Гостиная', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Прихожая',
    icon: 'hallway.svg',
    link: 'ideas',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Прихожая', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Кухня',
    icon: 'kitchen.svg',
    link: 'about',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Кухня', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Детская',
    icon: 'сhildrens_room.svg',
    link: 'store',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Детская', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Кабинет',
    icon: 'cabinet.svg',
    link: 'store',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Кабинет', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Товары для дома',
    icon: 'home.svg',
    link: 'store',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Кабинет', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
  {
    title: 'Мебель для дачи',
    icon: 'cottage.svg',
    link: 'store',
    img: 'react/static/img/submenu-img.jpg',
    dropDown: [
      {
        name: 'Тип',
        link: '',
        items: [
          { title: 'Кабинет', link: 'ideas' },
          { title: 'Прямые диваны', link: 'ideas' },
          { title: 'Угловые диваны', link: 'ideas' },
          { title: 'Модульные диваны', link: 'ideas' },
          { title: 'Конструктор диванов', link: 'ideas' },
          { title: 'Распродажа диванов', link: 'ideas' },
          { title: 'Кресла', link: 'ideas' },
          { title: 'Кушетки', link: 'ideas' },
          { title: 'Бескаркасная мебель', link: 'ideas' },
          { title: 'Пуфы', link: 'ideas' },
          { title: 'Домашний текстиль', link: 'ideas' },
        ],
      },
      {
        name: 'Размер',
        link: '',
        items: [
          { title: 'Одноместные', link: 'ideas' },
          { title: 'Двухместные', link: 'ideas' },
          { title: 'Трёхместные', link: 'ideas' },
          { title: 'Четырёхместные', link: 'ideas' },
        ],
      },
      {
        name: 'Стиль',
        link: '',
        items: [
          { title: 'Кантри', link: 'ideas' },
          { title: 'Классический', link: 'ideas' },
          { title: 'Лофт', link: 'ideas' },
          { title: 'Минимализм', link: 'ideas' },
          { title: 'Прованс', link: 'ideas' },
        ],
      },
      {
        name: 'Тип обивки',
        link: '',
        items: [
          { title: 'Натуральная кожа', link: 'ideas' },
          { title: 'Ткань', link: 'ideas' },
          { title: 'Экокожа', link: 'ideas' },
        ],
      },
    ],
  },
];

export const userMenu: IUserMenu[] = [
  {
    title: 'Войти/зарегистрироваться',
    icon: 'user.svg',
  },
  {
    title: 'Адреса магазинов',
    icon: 'shops.svg',
  },
  {
    title: 'Доставка и оплата',
    icon: 'delivery.svg',
    link: 'delivery',
  },
  {
    title: 'Ваш город',
    icon: 'location.svg',
  },
];
